# Toggle display sleep with power key
bindsym --locked --no-repeat XF86PowerOff output DSI-1 power toggle

# Map touchscreen to display
input 1739:0:Synaptics_TD4328 map_to_output DSI-1

# Start a terminal and virtual keyboard
exec foot -f monospace:size=14
exec wvkbd-mobintl -L 200
